services:
  postgres:
    image: postgres:17
    container_name: movie-pg
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moviedb
    ports:
      - "5432:5432"
    volumes:
      - movie-pg-data:/var/lib/postgresql/data
volumes:
  movie-pg-data: