spring.application.name=movie-platform
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
tmdb.api.key=${TMDB_API_KEY:}

# H2 (without docker)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:moviedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# PostgreSQL (with docker)
# spring.datasource.url=jdbc:postgresql://localhost:5432/moviedb
# spring.datasource.username=user
# spring.datasource.password=password
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


