spring.application.name=movie-platform
spring.profiles.active=local

# The origin of the frontend application that is allowed to make cross-origin requests.
# Change this to your production frontend URL when deploying (e.g. https://myapp.com).
cors.allowed-origin=http://localhost:3000
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
tmdb.api.key=${TMDB_API_KEY:}

# Ollama (local)
spring.ai.openai.api-key=ollama
spring.ai.openai.base-url=http://localhost:11434
spring.ai.openai.chat.options.model=gemma3:1b
spring.ai.openai.chat.options.temperature=0.4

#Gemma 4
#spring.ai.openai.chat.options.model=gemma4
#spring.ai.openai.chat.options.temperature=0.4

server.port = 8081
# H2 (without docker)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:moviedb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

#PostgreSQL (with docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/moviedb
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

logging.file.name=logs/app.log
logging.level.com.ivan.projects.movieplatform=DEBUG

